import{a as L,S as w,i as n}from"./assets/vendor-Qob_5Ba8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function p(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=p(t);fetch(t.href,o)}})();const g=async(r,e)=>{const c=`https://pixabay.com/api/?key=28678786-a2e7b218e16ae31de09ab66ee&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${e}`;try{return(await L.get(c)).data}catch(t){throw console.error("Error fetching data:",t),t}};function f(r){return r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image">
          <div class="info">
              <p><b>Likes</b> <span>${e.likes}</span></p>
              <p><b>Views</b> <span>${e.views}</span></p>
              <p><b>Comments</b> <span>${e.comments}</span></p>
              <p><b>Downloads</b> <span>${e.downloads}</span></p>
          </div>
      </a>
  `).join("")}function v(){document.querySelector(".gallery").innerHTML=""}const q=document.querySelector(".search-form"),y=document.querySelector(".gallery"),h=document.querySelector("#loader"),b=new w(".gallery a"),m=document.querySelector(".loader-more"),s=document.querySelector(".load-button");let a=1,d="",l=0,i=0;s.classList.add("hidden");m.classList.add("hidden");q.addEventListener("submit",r=>{if(r.preventDefault(),d=document.querySelector(".input").value.trim(),!d){n.warning({message:"Please enter a search term",position:"topRight",backgroundColor:"#FF0000",color:"white",timeout:5e3});return}v(),s.classList.add("hidden"),h.classList.remove("hidden"),a=1,i=0,g(d,a).then(e=>{if(l=e.totalHits,i=e.hits.length,l===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",color:"white",timeout:5e3}),h.classList.add("hidden");return}y.innerHTML=f(e.hits),a++,b.refresh(),i<l&&s.classList.remove("hidden")}).catch(e=>{n.error({message:"Error fetching images. Please try again later.",position:"topRight",backgroundColor:"#FF0000",color:"white",timeout:5e3})}).finally(()=>{h.classList.add("hidden")})});s.addEventListener("click",()=>{s.classList.add("hidden"),m.classList.remove("hidden"),g(d,a).then(r=>{i+=r.hits.length,i>=l&&(s.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"white",timeout:5e3})),y.insertAdjacentHTML("beforeend",f(r.hits)),a++,b.refresh()}).catch(r=>{n.error({message:"Error loading more images. Please try again later.",position:"topRight",backgroundColor:"#FF0000",color:"white",timeout:5e3})}).finally(()=>{var r;if(m.classList.add("hidden"),i<l){s.classList.remove("hidden");const e=((r=document.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height)||100;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}})});
//# sourceMappingURL=index.js.map
